language: node_js
sudo: required
dist: trusty
addons:
  chrome: stable
before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
cache: yarn
notifications:
  email: false
node_js:
  - '10'
  - '8'
script:
  - yarn test && yarn travis-deploy-once "yarn semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
